// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherDataService.Data;

#nullable disable

namespace WeatherDataService.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20250312194636_Last-Updated")]
    partial class LastUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("WeatherDataService.Models.Current", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("temperature_2m")
                        .HasColumnType("REAL");

                    b.Property<int>("weather_code")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Current");
                });

            modelBuilder.Entity("WeatherDataService.Models.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("currentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("currentId");

                    b.ToTable("WeatherData");
                });

            modelBuilder.Entity("WeatherDataService.Models.WeatherData", b =>
                {
                    b.HasOne("WeatherDataService.Models.Current", "current")
                        .WithMany()
                        .HasForeignKey("currentId");

                    b.Navigation("current");
                });
#pragma warning restore 612, 618
        }
    }
}
